//
// Created by Iordan Tonchev on 10.10.21.
//

#ifndef SDL_GAME_SDL_DEFAULT_APP_SETTINGS_H
#define SDL_GAME_SDL_DEFAULT_APP_SETTINGS_H

#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 480
#define MUSIC_VOLUME 100
#define MUSIC_SFX 100

#endif //SDL_GAME_SDL_DEFAULT_APP_SETTINGS_H
